Fix compilation on clang
There are two definitions of the function "classify":
- bucket_type classify(const value_type&, int)
- template <typename Yield> void classify(iterator, iterator, int, Yield&&)

Only the latter is a template, so specifying `template` here is wrong.
This causes compile errors on clang:

> error: no matching member function for call to 'classify'
> ...
> error: assigning to 'int' from incompatible type 'void'

Removing `template` fixes this.